Makefile

Signed-off-by: Leo Chen <leo@harmony.one>

[makefile] add GO111MODULE env variable

---

cmd/subcommands/transfer.go

As requested by @fxfactorial ([comment](https://github.com/harmony-one/harmony/pull/1702#issuecomment-540050139)) I've ported the validation logic that was merged into harmony/master (pull request: https://github.com/harmony-one/harmony/pull/1702) into this repo.
It seems that addresses are already getting validated so didn't touch any code relating to that.
There was no validation in place for shardIDs so I've implemented that:
```
$ hmy transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --from-shard 99 --to-shard 99 --amount 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4516710]
goroutine 1 [running]: …
```

Improve validation of shardIDs

---

pkg/sharding/structure.go

Add error handling on RPC request

Fix panic when GetBalance RPC request fails

---

cmd/subcommands/staking.go

Address this issue: https://github.com/harmony-one/go-sdk/issues/51

Added sanity check for issue 51

---

cmd/subcommands/blockchain.go
cmd/subcommands/delegation.go
cmd/subcommands/validator.go
pkg/rpc/methods.go

@gupadhyaya I organized the subcommands, let's work together tomorrow so you can adjust the parameters as needed

[staking] Organize subcommands for validator/delegation querying

---

cmd/subcommands/completion.go

Add bash completion subcommand

---

pkg/keys/bls.go

one time bls passphrase

---

cmd/subcommands/staking.go

Could not reuse the code in the transfer.go mainly because staking.go currently is not properly designed and has lot of code duplication. The duplication will be removed in another PR, hence adding this for temporary.

support wait-for-confirm flag for staking similar to normal transactions

---

cmd/subcommands/staking.go

* Fix for other staking commands as well

[#82] Undelegate command failing with nonce too low due to wrong address

---

README.md
cmd/subcommands/values.go

Update cookbook with recipes for all staking transactions to aid users
Update README to reflect new cookbook

[#89] Update cookbook

---

README.md
cmd/subcommands/blockchain.go
cmd/subcommands/request.go

* Returns transaction history for an account
* Update README & cookbook

[cli] Add transaction history command

---

pkg/sharding/structure.go

#101 
Remove extra comma from output when missing a reply when querying balances

Issue #101 Fix

---

cmd/subcommands/staking.go
cmd/subcommands/transfer.go
pkg/transaction/controller.go
pkg/transaction/transaction.go

```
$ hmyDev blockchain transaction-by-hash 0x5f0a42cafeffa9ab7519f1d758b5841937d4bbda2b606b7a5dccb500ce2d6a29
{
"id": "0",
"jsonrpc": "2.0",
"result": {
"blockHash": "0x038aa962b4656e0af7987a6583de7c7161290d004150b9aeb133857ba879b78e",
"blockNumber": "0x671",
"from": "one1leh3g2036lxp3rc2xytcc508d58dn273mtrq5m",
"gas": "0x5208",
"gasPrice": "0x3b9aca00",
"hash": "0x5f0a42cafeffa9ab7519f1d758b5841937d4bbda2b606b7a5dccb500ce2d6a29",
"input": "0x",
"nonce": "0x0",
"r": "0x27ebcd8e8c6700b762a40b38a0a482670930a8103295543e251b83be6dde9511",
"s": "0x249c7178b2a4037d55d4c293d51d09b66abab04459af644b9007e113cbdd1386",
"shardID": 0,
"timestamp": "0x5e1f9e5c",
"to": "one13ylq9j90c3kafe8avc8l87m0w705z65dyhnp8a",
"toShardID": 0,
"transactionIndex": "0x1",
"v": "0x29",
"value": "0xde0b6b3a7640000"
}
} …
```

[gas] Take gas-price input in NANO

---

cmd/subcommands/staking.go

Reverts harmony-one/go-sdk#128

Revert "updating edit-validator to allow modifying one field at a time"

---

README.md
cmd/subcommands/blockchain.go
pkg/rpc/methods.go

Expose utility metrics to go-sdk.

Expose utility metrics to go-sdk

---

pkg/common/numeric.go

[pkg/common] Fix edge case hex conversion #134

---

.gitignore
cmd/subcommands/staking.go
cmd/subcommands/transfer.go
go.mod
go.sum
pkg/keys/bls.go
pkg/transaction/controller.go

Do **NOT** merge until new harmony release.

[#2257] Use core.IntrisicGas calculations for default gasLimit

---

cmd/subcommands/balance.go
cmd/subcommands/blockchain.go
cmd/subcommands/delegation.go
cmd/subcommands/keys.go
cmd/subcommands/root.go
cmd/subcommands/validator.go
pkg/store/local.go

TODO: Not avail for transactions & staking transactions

[#2252] Enable account alias for commands

---

cmd/subcommands/utility.go

Get sharding structure from node endpoint to determine shard of BLS key

Add feature to get shard of BLS key with node endpoint

---

cmd/subcommands/validator.go
cmd/subcommands/values.go
pkg/rpc/methods.go

Backend is changed from active to elected, hence changing the cli too.

change active to elected

---

cmd/subcommands/keys.go

```
$ ./hmy keys add new_acc
**Important** write this seed phrase in a safe place, it is the only way to recover your account if you ever forget your password
[mnemonic]
ONE Address: one1u98m9eup7jexkpvecqjhlaefzh0yg7aea5avk6
```

[keys] Print ONE Address after wallet creation & imports

---

cmd/subcommands/keys.go

This should fix the passphrase from file issue in #166

[cmd] Fix getting passphrase from file #166

---

cmd/subcommands/values.go

It is a proposal from the community of volunteers to update the cookbook while they are still using it. I would submit another update once we move to mainnet

Change API to OSTN for cookbook

---

cmd/subcommands/balance.go
pkg/rpc/methods.go

* Add getShardID RPC
* Use getShardID instead of getNodeMetadata

[#176] Fix panic when querying node for balance

---

cmd/subcommands/blockchain.go
cmd/subcommands/root.go
cmd/subcommands/utility.go
cmd/subcommands/values.go
pkg/rpc/methods.go

* [#164] Require exactly 1 argument for account-history
* Add GetLastCrossLinks RPC to utility
* Check if node input is an harmony api endpoint
* [#174] Make cookbook function of node input, default Mainnet
```
$ hmy --node=https://api.s0.os.hmny.io utility last-cross-links
{
"id": "0",
"jsonrpc": "2.0",
"result": [
{
"blockNumber": 831,
"epochNumber": 10,
"parentHash": "0x14cfec39242379a8606ed261464db1115bd6d91f1546b94de4fdc48621470816",
"shardId": 1,
"signature": "f1baf4f8320f759b41f30248ef3623fd7d40b386698a3c393e7b6a671f6340050f0050a3d7468a897c68101c4a9e44013a0cda5c1bd59ab9b69a973c81e8edb752076e2b87b315c46533076598fb07dbd97827f915df8d5f067378f6066dee87",
"signatureBitmap": "ffffff5f"
},
{
"blockNumber": 839,
"epochNumber": 10,
"parentHash": …
```

Minor CLI fixes & features

---

cmd/subcommands/utility.go

./hmy utility
shards         sharding structure and end points
Signed-off-by: Leo Chen <leo@harmony.one>

[utility] add shards command

---

cmd/subcommands/root.go

Addresses https://github.com/harmony-one/harmony/issues/2447

[root] Detect default chainid from localhost using getShardingStructure

---

Makefile
cmd/subcommands/root.go

[make] Check operating system before uploading

[root] Fix version check on error

---

cmd/subcommands/staking.go
go.mod
go.sum
pkg/keys/bls.go

1. Update harmony-one/harmony to latest version
2. Fix updated bls references, from Bls -> BLS

Update to latest harmony-one/harmony + fix BLS naming

---

pkg/keys/bls.go

Fix updated bls references, from Bls -> BLS -- This fixes failed build of newly merged multiple BLS keys commit

Fix updated bls references, from Bls -> BLS

---

cmd/subcommands/validator.go
pkg/rpc/methods.go

[cli] Remove command for deleted RPC

[rpc] Remove deleted hmy_getValidatorMetrics RPC

---

scripts/hmy-csv.py

0) (Optional) Open terminal and `cd` to wherever you want to install your CLI. Personally I like `~/bin`.
```bash
mkdir -p ~/bin && cd ~/bin
```
1) Get the latest Harmony CLI version
```bash
curl -O https://raw.githubusercontent.com/harmony-one/go-sdk/master/scripts/hmy.sh && chmod +x hmy.sh && hmy.sh -d
```
2) Install the CSV parser script **in the same directory**
```bash
curl -O https://raw.githubusercontent.com/harmony-one/go-sdk/master/scripts/hmy-csv.py && chmod +x hmy-csv.py
```
> Note that this will require python 3.6 or newer. You can check this with the following command `python3 --version`.
3) Create your CSV file (with numbers, excel, sheets, etc..), make sure to follow [this](https://docs.google.com/spreadsheets/d/1nkF8N16S3y28cn7SM1cYJca8lzHPOzyR42S1V-OOAeQ/edit#gid=0) …

[scripts] Add CSV transaction wrapper script

---

cmd/subcommands/staking.go

Needed for scripts using Decimal (Python)

[staking] Use scientific notation parser for commission rates

---

cmd/subcommands/keys.go
pkg/account/export.go

Command:
```
hmy keys check-passphrase <ONE_ADDRESS>
```

Add Passphrase check for keystore wallet

---

scripts/hmy.sh

release static binary by default
Signed-off-by: Leo Chen <leo@harmony.one>

[release] do not download library

---

cmd/subcommands/staking.go

This is a hotfix for https://github.com/harmony-one/harmony/issues/3462.

[Staking] Verify BLS key input

---

.github/workflows/hmybuild.yml

This github action will auto build the hmy binary for amd64 and arm64, when code with a tag starting with v is pushed. e.g. v1.2.3

Created github actions build for hmy (arm and amd)

---

pkg/governance/api.go
pkg/governance/cli.go

fix https://github.com/harmony-one/go-sdk/issues/255 and #256

fix hmy governance not working

---

README.md
cmd/subcommands/root.go
cmd/subcommands/transfer.go
pkg/transaction/controller.go
pkg/transaction/ethcontroller.go

https://github.com/harmony-one/go-sdk/issues/251

Offline signing

---

.github/workflows/hmybuild.yml

Upgrade golang version and fix actions

Upgrade golang version and fix actions 

---

pkg/account/import.go

fix issue 187

---

cmd/subcommands/governance.go

fix issue 248

---

cmd/subcommands/root.go

fix issue 247

---

pkg/governance/cli.go

For issue https://github.com/harmony-one/go-sdk/issues/277

Optimize the prompt when rpc error time

---

Makefile
go.mod
go.sum

This PR upgrades the go to version 1.22.5

upgrade go to version 1.22.5
