cmd/subcommands/keys.go, pkg/account/creation.go, pkg/keys/mnemonic.go, pkg/keys/mnemonic_test.go
To follow exactly what the JS SDK does, the bip39 new seed call has to have an empty string passphrase. Moreover, the addition of the index field is there just in case it is needed in the future. The index is hardcoded to 0 at the moment.
=> [mnemonic] Enable recover from mnemonic with unused index

cmd/subcommands/keys.go, pkg/account/creation.go, pkg/account/import.go, pkg/common/values.go, pkg/store/local.go, test.sh
Given a secp256k1 private key, like the one generated from the following command:
```
openssl ecparam -genkey -name secp256k1 -text -noout -outform DER | xxd -p -c 1000 | sed 's/41534e31204f49443a20736563703235366b310a30740201010420/PrivKey: /' | sed 's/a00706052b8104000aa144034200/\'$'\nPubKey: /'
```
You can import the key with an optional name and passphrase. For example:
```
./hmy keys import-private-key b8798ca0a56ce16517ea37c6b1229cbb67cf0e022c423b044fe8f537830d8be5 foo-bar-baz --passphrase
```
=> Import keys using secp256k1 private keys.

cmd/subcommands/custom-flags.go, cmd/subcommands/transfer.go, pkg/validation/validation_test.go, pkg/validation/validator.go
This is a continuation of https://github.com/harmony-one/go-sdk/pull/29.
I refactored the shardID validation methods into pkg/validation/validator.go and I also added the address validation functionality from the previous pull request I made to harmony-one/harmony (https://github.com/harmony-one/harmony/pull/1702).
The test from that PR has also been ported over and is also included in this PR.
```
$ hmy transfer --from FOOBAR --to one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --from-shard 0 --to-shard 0 --amount 1
Error: invalid argument "FOOBAR" for "--from" flag: not a valid one address: cannot decode "FOOBAR" as bech32 address: decoding bech32 failed: invalid bech32 string length 6
```
```
$ hmy transfer --from one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --to FOOBAR --from-shard 0 …
```
=> pkg/validation: Validation methods for addresses and shardIDs

.gitignore, cmd/subcommands/staking.go, go.mod, go.sum, pkg/ledger/hw_wallet.go, pkg/ledger/nano_S_driver.go, pkg/rpc/methods.go
Support all 5 commands in CLI for staking: 
```
./hmy staking delegate --delegator one1q6gkzcap0uruuu8r6sldxuu47pd4ww9w9t7tg6  --validator one15l3pj0v9a8gfkdatd5hpj029kvc4mlr6r5djmg --gas-price 2  --staking-amount 12345 --passphrase "harmony-one" --ledger
{"transaction-receipt":"0xde39174ce840a2c4addc40820dc1350e380ce64bc87362820493ac19a63325d3"} 
```
```
./hmy staking newvalidator --amount 123 --details details --gas-price 20 --identity identity --max-change-rate 12.22 --max-rate 1.2 --min-self-delegation "32.10" --name name  --pubkey 111111111111111111111111111111111111111111111111 --rate "12.2" --security-contact smith --staking-addr one1sl6hku7wxgxnhajrc0a96p6zpea6qr0p0sqajk --website harmony.one --passphrase "harmony-one"
{"transaction-receipt":"0x3e07eb4a2f2e9401623d23c86f9c819828e63 …
```
=> Added stake support in CLI and ledger HW signing

cmd/subcommands/keys.go, pkg/account/export.go, pkg/account/import.go
Given an account's address **in the CLI's Keystore**, we can export its secp256k1 private key with the following command:
```
./hmy keys export-private-key one1a7tlnl08s978687zjsdns3m5dckdm0hnxxlwkt
```
We can export the Keystore contents with the following command:
```
./hmy keys export-ks one1a7tlnl08s978687zjsdns3m5dckdm0hnxxlwkt
```
=> Add export for account's secp256k1 private key and keystore file

cmd/subcommands/staking.go, go.mod, go.sum, pkg/ledger/nano_S_driver.go
1) Updated command line options based on the latest staking message format (Harmony version 110619)
2) Fixed a bug in staking max rate
3) Updated Ledger driver for staking txn to support multiple packets per Txn
=> Updated staking support for CLI

cmd/subcommands/blockchain.go, cmd/subcommands/keys.go, cmd/subcommands/staking.go, cmd/subcommands/values.go, pkg/account/import.go, pkg/common/values.go, pkg/keys/bls.go
We can now generate BLS keys (as well as encrypt and save the private BLS key) with the following command:
```
./hmy keys generate-bls-key --bls-file-path /tmp/file.key
```
**Moreover, the following wallet BLS functionalities have been implemented in the CLI:**
* Recover BLS keys from the saved private key file mentioned above. This is compatible with saved BLS keys from the main repo's wallet binary. 
```
./hmy keys recover-bls-key /Users/danielvdm/go/src/github.com/harmony-one/harmony/.hmy/02c8ff0b88f313717bc3a627d2f8bb172ba3ad3bb9ba3ecb8eed4b7c878653d3d4faf769876c528b73f343967f74a917.key --passphrase=''
```
* Encrypt and Save a BLS private key
```
./hmy keys save-bls-key 89f48af29edf71f65a58993a14588d6d1369430a2f208e07e1d1b27be0f30449 --bls-file-path /tmp/test.key
```
* Get public BLS …
=> Add staking tools and add BLS tools

cmd/subcommands/staking.go
tested both with and without 0x prefix in BLS pub keys.
./hmy staking create-validator --amount 10 --validator-addr one1sl6hku7wxgxnhajrc0a96p6zpea6qr0p0sqajk  --bls-pubkeys 678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c,6757ebfbbc53a167e4c069cdf2beecd1428316306145c8d6d97c6c6babb3ec34e7003b3db8ccfc7d79a412aec7c68c97  --identity foo --details bar --name baz --max-change-rate 10 --max-rate 10 --max-total-delegation 10 --min-self-delegation 10 --rate 10 --security-contact Leo --website lol.com --passphrase='harmony-one'
{"transaction-receipt":"0xe9eb9c77e42ef289593de2b537460fcee06c54ec7fab39ba9ba54b5db478fadc"}
./hmy staking create-validator --amount 10 --validator-addr one1sl6hku7wxgxnhajrc0a96p6zpea6qr0p0sqajk  --bls-pubkeys …
=> Add support for 0x prefix in BLS pub keys

cmd/subcommands/staking.go
For issue https://github.com/harmony-one/go-sdk/issues/50. 
Use the rlp encoded staking data field to get the gaslimit 
gas, err := IntrinsicGas(st.data, contractCreation, homestead)
https://github.com/harmony-one/harmony/blob/2b91eea32d5cd4fbac8dfb7cba37300031407773/core/state_transition.go#L213
=> updated gaslimit algorithm for staking contracts

cmd/subcommands/keys.go, pkg/common/values.go
* Passphrase is now required when using import-ks
* Passphrase flag for add is changed to use-own-passphrase which accepts a bool
- to differentiate from the string input passphrase flag
=> [#67] Change default passphrase to empty string

cmd/subcommands/staking.go
Amount is less than max (if max is not 0) and greater than min
=> [#73] Fix logic for sanity check on create-validator fields

cmd/subcommands/balance.go, cmd/subcommands/transfer.go
* Request to particular IP when given instead of API endpoint
* Returns balance only for shard that node is on
* Sends transaction to node indicated by --node, must match --from-shard for tx to succeed
=> [#81] Check for IP input on --node for balance and transfer commands

cmd/subcommands/staking.go, cmd/subcommands/transfer.go, pkg/transaction/controller.go, pkg/transaction/transaction.go
For a regular transaction, if no nonce option is provided, it should now correctly set the next nonce (previously underflowed to max val of `uint64`). Moreover, one could only set the nonce to at most the max of `int64`. This PR should now allow one to set the nonce to up to the max of `uint64`.
=> Nonce control fix.

pkg/keys/bls.go
It is confusing to display public-key and private-key with `0x` when user generates bls keys using `hmy keys generate-bls-key` command. Hence, removing it.
=> remove 0x from public-key/private-key display part of generate-bls-key

cmd/subcommands/keys.go, pkg/account/account_test.go, pkg/account/removal.go
This PR adds support for removing a named account from the keystore.
The PR adds a new subcommand to the "keys" command, e.g:
`./hmy keys remove foobar`
A unit test is also included, run it using `cd pkg/account && go test . && cd ../..`
=> Add support for removing an account from the keystore

cmd/subcommands/staking.go, cmd/subcommands/transfer.go, pkg/common/numeric.go, pkg/transaction/controller.go, pkg/transaction/transaction.go
* Replace big.Int with numeric.Dec to enable enough precision for Atto transactions
* Check transaction amount + gas price when verifying existing balance before transactions
* Enable scientific notation input
* Enable user to input desired gas-price & gas-limit
* Set default gas to 1 Gwei
* Calculate gas-price based on gas-limit
Staking transaction is currently untested.
=> [harmony #2057] Enable Atto precision transactions using the CLI

cmd/subcommands/balance.go
```
$ ./hmy --node=https://api.s0.pga.hmny.io balances onedeadbeef
Error: address supplied (onedeadbeef) is not valid
v1975e5a5a5-dirty: address supplied (onedeadbeef) is not valid
```
=> [#104] Check for valid  one address input for querying balances

cmd/subcommands/keys.go, pkg/account/import.go
* Use given passphrase when encrypting imported ks
* Allow the use of relative paths
* Update help doc for `keys import-ks`
=> Encrypt imported keystore file with given passphrase

README.md, cmd/subcommands/keys.go, cmd/subcommands/root.go, cmd/subcommands/staking.go, cmd/subcommands/transfer.go, cmd/subcommands/values.go, pkg/account/import.go, pkg/store/local.go, pkg/transaction/controller.go
* All passphrase related commands have 3 options. 1) use default passphrase (unchanged). 2) use passphrase from a file via the `passphrase-file` option. 3) provide passphrase interactively when the `passphrase` option it toggled. 
* Batched transactions now logs/returns relevant information from `transaction.Controller` instead of explicit fields. Note that single transaction JSON keys have not been changed for regular transactions. However, `dry-run` transactions now have the raw transaction in one JSON object. 
Batched transaction documentation added to README for reference:
One may find it useful to send a batch of transaction with 1 instance of the binary.
To do this, one can specify a JSON file with the `transaction` subcommand to dictate a batch of transaction to send off **in …
=> Address issue #119 & #120 and make batched transaction more general + docs

pkg/account/import.go, pkg/store/local.go
I didn't found a very good way to obtain the ONE address without importing it first. Hence the need to create that new method DoesAddressExistTwice and remove the account from the keystore if the ONE address is found twice.
Please suggest if there is a better way to do this.
```
root@48e98e352df0:~/go/src/github.com/harmony-one/go-sdk# dist/hmy keys list
NAME                                                    ADDRESS
root@48e98e352df0:~/go/src/github.com/harmony-one/go-sdk# dist/hmy keys import-ks $(pwd)/UTC--2020-01-25T20-50-41.577244708Z--8ceda0fd494b2848fbb64b083409a7c1dcce3bfb
Imported keystore given account alias of `thunder-imported`
root@48e98e352df0:~/go/src/github.com/harmony-one/go-sdk# dist/hmy keys list
NAME                                                    ADDRESS …
```
=> Adding support to avoid having the same keystore file added twice

cmd/subcommands/validator.go
```
$ hmyStaking blockchain validator metrics one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t
{
"id": "0",
"jsonrpc": "2.0",
"result": {
"blocks-jailed": 0,
"bls-keys-per-shard": [
{
"bls-public-keys": [
"a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882"
],
"shard-id": 0
}
],
"total-effective-stake": "11500000000000000000.000000000000000000",
"voting-power-per-shard": [
{
"shard-id": 0,
"voting-power": "0.023365079365079365"
}
]
}
}
```
```
$ hmyStaking blockchain validator metrics one1txy0a2szxlk7z0dvvfgv24kjjv60w2mcnyfl8a
commit: v265-7782446-dirty, error: Catch all RPC error: validator stats not found: 0x5988fEaa0237EDe13DaC6250C556d29334F72B78
check hmy cookbook for valid examples or try adding a `--help` flag
```
=> [#2197] Fix blockchain validator metrics command

cmd/subcommands/root.go, cmd/subcommands/validator.go
```
$ hmyStaking blockchain validator metrics one1txy0a2szxlk7z0dvvfgv24kjjv60w2mcnyfl8a
Metrics are only available for Validators that have participated in consensus committee.
commit: v266-558cc6b-dirty, error: Catch all RPC error: validator stats not found: 0x5988fEaa0237EDe13DaC6250C556d29334F72B78
check hmy cookbook for valid examples or try adding a `--help` flag
```
=> [#2197] Add clarification for errors message on blockchain validators metrics

cmd/subcommands/staking.go, cmd/subcommands/transfer.go, pkg/transaction/controller.go, pkg/transaction/errors.go, pkg/transaction/transaction.go
Currently, in the CLI, regular transactions don't report errors from the error sink in the errors JSON array if they timeout. This PR implements this. In the processes I did the following:
* Add functionality to get Errors by Hash in the SDK (works for both staking and regular txs)
* Refactor the transaction controller to fetch tx errors on timeout and expose a method to access the errors. 
* Refactor the transaction controller to take data as a byte slice instead of a string
* Change the `wait-for-confirm` to `timeout` but always enable wait for confirming. One can set timeout to 0 to just send the tx with waiting for it to finalize.
* Change 'transaction-receipt' to 'transaction-hash' for clarity.
A successful transaction (with timeout 40 sec enabled by default) now looks like:
```bash …
```
=> Add txn error fetch from error sink to SDK and plain txn Controller

README.md, cmd/main.go, cmd/subcommands/keys.go, cmd/subcommands/values.go
```
deprecated method: use `./hmy keys recover-from-mnemonic` instead.
```
=> [#2296] Make recover-from-mnemonic a separate command

cmd/subcommands/root.go
closes #158 
- In the PersistentPreRun method of the root command:
- Add if/else statement to catch endpoint urls
- Add switch statement to handle missing protocol or port/protocol and port.
=> add logic to add protocol and port to node ip

cmd/subcommands/root.go
- Previous logic did not account for passing an endpoint with a protocol as node.
- https://api.s0.os.hmny.io/ would fail
- Added a check for TLS protocol.
=> patch node leniency to handle endpoints

cmd/subcommands/root.go
- Previously, not including a port while using http as the protocol would lead to appending a port (9500)
- Now, node is not changed if protocol is explicit.
=> Modify node leniency to respect protocol default ports

Makefile, cmd/subcommands/validator.go
```
$ hmyStaking blockchain validator information one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur
commit: v342-7dbc13e-dirty, error: validator address not found: one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur
check hmy cookbook for valid examples or try adding a `--help` flag
```
=> [#180] Better error message for validator information not found

cmd/subcommands/blockchain.go, pkg/rpc/methods.go
```
$ hmy blockchain latest-headers --node=127.0.0.1:9511
{
"id": "0",
"jsonrpc": "2.0",
"result": {
"beacon-chain-header": {
"block-header-hash": "0xf8fe4304edebe73a4ecd844fb80e0a72d3619ecfd68f7ad7d46b1a1b78deddc1",
"block-number": 19,
"epoch": 2,
"shard-id": 0,
"view-id": 19
},
"shard-chain-header": {
"block-header-hash": "0x5da27afe7dd61786186998f1959a538dc196438782b6edc34eb7028d43111aad",
"block-number": 19,
"epoch": 2,
"shard-id": 1,
"view-id": 19
}
}
}
```
=> [blockchain] Add latest-headers command to get chain headers

cmd/subcommands/staking.go, pkg/common/values.go, pkg/keys/bls.go
This option can be used to automate the create-validator and
edit-validator actions. No need to manually input the path to the
blskeys and the passphrase.
--bls-pubkeys-dir <path> is used to specify the path to the bls pubkey
files and the passphrase files
the pubkey and passphrase files should follow the naming convention of
pubkey.key and pubkey.pass as a pair.
Signed-off-by: Leo Chen <leo@harmony.one>
=> [hmcli] add --bls-pubkeys-dir option

cmd/subcommands/keys.go, cmd/subcommands/root.go, cmd/subcommands/values.go, pkg/common/chain-id.go, pkg/keys/bls.go, pkg/keys/bls_test.go, pkg/validation/validation_test.go, pkg/validation/validator.go
Default to mainnet if the provided node is not alive for BLS keygen.
=> Add node check when generating BLS keys

README.md, cmd/subcommands/staking.go, cmd/subcommands/transfer.go, cmd/subcommands/values.go, pkg/transaction/transaction.go
Using the pending nonce allows for fast consecutive transfers when using the batch transaction file or if using `--timeout 0` flag. However, should one want to use the true nonce (from finalized transactions, i.e: the old way) the `--true-nonce` option has been added to do just that.
=> Use pending nonce over true nonce by default for txs

go.mod, go.sum, pkg/ledger/hw_wallet.go
This PR uses the latest `harmony-one/harmony` version which introduces a change to the `types.Transaction` API where `tx.Gas()` is changed to `tx.GasLimit()`.
=> Use latest harmony-one/harmony version, use new types.Transaction API

cmd/subcommands/ethtransfer.go, go.mod, go.sum, pkg/common/chain-id.go, pkg/transaction/ethcontroller.go, pkg/transaction/transaction.go
This PR adds support for sending Ethereum txs using go-sdk:
```
./hmy eth-transfer --from SENDER --to RECEIVER --amount 10 --chain-id 1666700000 --timeout 60 --node http://localhost:9500
```
---
Due to time restriction the code is mostly copy/paste of the previous tx controller code with modifications to get the Eth txs to work properly.
The code should get refactored at some point in the future, ideally when `harmony-one/harmony` is also refactored to use the `InternalTransaction`-interface wherever possible.
=> Add support for sending ethereum txs using go-sdk

README.md, cmd/subcommands/governance.go, cmd/subcommands/values.go
Improve governance command help strings by fixing grammar and adding more context around what "--key" is by describing it as an account address that needs to be imported via the private-key way.
=> Improve governance command help strings

go.mod, go.sum
The issue is related to https://github.com/fatih/color/issues/147
Manually tested able to build and run with go 1.17
close #269
=> fix(mod): update fatih/color for go 1.17 macos

pkg/governance/cli.go
Previously the Snapshot block was being randomly generated. This change pulls it from the Yaml instead.
Closes #274
=> Add a Snapshot field to new proposal yaml

cmd/subcommands/values.go
- Add `--passphrase` to `recover-from-mnemonic` command
Justification:
It is unclear this option is available and very important for CLI users to be setting passwords on their recovered keys.
=> Add Passphrase Flag to Mnemonic Recovery Cmd

pkg/ledger/nano_S_driver.go
Split the message to be signed into packets of size 255. The implementation is simply copied over from staking transaction signing.
Closes #297
See also harmony-one/staking-dashboard#637
=> pkg/ledger: fix transaction signing

.github/workflows/hmybuild.yml, .github/workflows/test-build.yml
this PR updates the github actions script :
- use ubuntu 22 as deprecation has been announced
- fix the macos build
=> [github action] ubuntu22 and fix macos build

.github/workflows/hmybuild.yml, .github/workflows/test-build.yml, pkg/governance/eip712.go, pkg/governance/types.go
- approval and ranked-choice (uint32[]) => []interface{}
- quadratic / weighted / shutter => unchanged
- single-choice => unchanged
- return error if unknown type
- remove panic when converting to uint64
- add examples as comments for each of the proposal types. these have been verified by comparing with snapshot.js output
```js
// "@snapshot-labs/snapshot.js": "0.4.16",
import snapshot from '@snapshot-labs/snapshot.js';
// "ethers": "5.7",
import { Wallet } from "ethers";
const hub = 'https://hub.snapshot.org';
const client = new snapshot.Client712(hub);
const signer = new Wallet("5a59d518386f3d11eaf978d1874bf7e3ba400f4c0b4ebd750250e6f4e26b15d5");
const receipt = client.vote(signer, "0x0F22ec8F25fA6EaBc8f8F6B3Eb0645f0e4ea43Bd", {
space: 'harmony-mainnet.eth',
proposal: …
```
=> governance: fix voting support for `approval` etc

cmd/subcommands/ethtransfer.go, cmd/subcommands/transfer.go, pkg/console/console.go, pkg/transaction/controller.go, pkg/transaction/ethcontroller.go, pkg/transaction/util.go
Supersedes #287 
Example:
```py
#!/usr/bin/python3
from pyhmy import signing
tx = {
'chainId': 1666700000,
'data': "0xabcd",
'gas': 21000,
'gasPrice': 100000000000,
'nonce': 0,
'to': "0x19e7e376e7c213b7e7e7e46cc70a5dd086daff2a",
'value': 1000000000000000000
}
print(
signing.sign_transaction(
tx,
"0x1111111111111111111111111111111111111111111111111111111111111111"
).rawTransaction.hex()
)
```
Produces output
`0xf8728085174876e8008252089419e7e376e7c213b7e7e7e46cc70a5dd086daff2a880de0b6b3a764000082abcd84c6afa5e4a0e85acf7a47cbd55a47bd778f3dc0446db45343fc3ef3a998f4449b2b58fcf1baa07af989a4543bfcae3746b6d59df4704e279721017946c8f9d46b150bc5787786`
The same transaction signed using `hmy`
```bash
$ hmy eth-transfer --offline-sign --nonce=0 --from=one1r8n7xah8cgfm0el8u3kvwzja6zrd4le2ntjy82 …
```
=> [console/cmd] add support for `data` signing

cmd/subcommands/keys.go, pkg/account/creation.go, pkg/keys/mnemonic.go, pkg/keys/mnemonic_test.go
Updated features for `hmy keys recover-from-mnemonic`:
- The `coinType` flag is used when performing key derivation from mnemonic.
- BIP 44 uses key derivation to generate multiple keys from a single mnemonic for different cryptocurrencies. The coinType flag specifies which cryptocurrency's keys to derive (e.g., 1023 for Harmony, 60 for Ethereum). 
- Required for Metamask mnemonic, as they use type coin type `60` across all networks.
- The `index` flag is used to specify which key is to be recovered from mnemonic.
=> Recovery Using Mnemonic
